
const SCENARIO=window.SCENARIO,KEY="cic_v17";
let state=JSON.parse(localStorage.getItem(KEY)||"null")||{started:false,center:SCENARIO.defaultCancerCenter,type:"mosaiq-conversion",phase:0,obs:0,health:null,check:{},notes:{},reveal:{},done:{}};
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function t(){return SCENARIO.scenarioTypes.find(x=>x.id===state.type)||SCENARIO.scenarioTypes[1]}
function p(){return SCENARIO.phases[state.phase]}
function o(){return p().observations[state.obs]}
function reset(){localStorage.removeItem(KEY);location.reload()}
function setType(id){state.type=id;state.health={...(SCENARIO.scenarioTypes.find(x=>x.id===id)||t()).health};save();render()}
function start(){state.center=document.getElementById("center").value.trim()||SCENARIO.defaultCancerCenter;state.started=true;state.health={...t().health};save();render()}
function setPhase(i){state.phase=i;state.obs=0;save();render()}
function nextObs(){if(state.obs<p().observations.length-1)state.obs++;else if(state.phase<SCENARIO.phases.length-1){state.done[p().id]=true;state.phase++;state.obs=0}save();render()}
function prevObs(){if(state.obs>0)state.obs--;save();render()}
function toggleCheck(i){let k=p().id+":"+i;state.check[k]=!state.check[k];save();render()}
function pct(){let list=p().checklist,total=list.length,done=list.filter((_,i)=>state.check[p().id+":"+i]).length;return total?Math.round(done/total*100):0}
function note(field,val){state.notes[p().id+":"+state.obs+":"+field]=val;save()}
function getNote(field){return state.notes[p().id+":"+state.obs+":"+field]||""}
function reveal(){state.reveal[p().id+":"+state.obs]=true;save();render()}
function isRevealed(){return state.reveal[p().id+":"+state.obs]}
function health(){let vals=Object.values(state.health||t().health),avg=Math.round(vals.reduce((a,b)=>a+b,0)/vals.length);return avg>=75?"Green":avg>=45?"Yellow":"Red"}
function landing(){return `<header><h1>${esc(SCENARIO.appName)}</h1><p>CIC Apprenticeship Platform</p></header><div class="landing"><div class="card"><h2>Create Simulated Project</h2><div class="field"><label>Cancer Center Name</label><input id="center" value="${esc(state.center)}"/></div><h3>Project Pathway</h3><div class="template-grid">${SCENARIO.scenarioTypes.map(x=>`<div onclick="setType('${x.id}')" class="template ${state.type===x.id?'selected':''}"><strong>${esc(x.name)}</strong><div class="meta">${esc(x.difficulty)}</div><p>${esc(x.description)}</p><div class="result"><strong>Current:</strong> ${esc(x.currentOIS)}<br><strong>Future:</strong> ${esc(x.futureOIS)}</div></div>`).join("")}</div><button class="primary" onclick="start()">Launch Academy</button><div class="result"><strong>Content editing:</strong> Most simulator content now lives in <code>data/scenario.json</code>. Edit that file to add phases, checklist items, observations, questions, and Senior CIC perspectives.</div></div></div>`}
function sidebar(){return `<aside class="card sidebar"><h2>${esc(state.center)}</h2><div class="meta">${esc(t().name)}</div><p>Project Health: <span class="pill yellow">${health()}</span></p>${Object.entries(state.health||t().health).map(([k,v])=>`<div class="health-row"><span>${esc(k)}</span><div class="bar"><div class="fill" style="width:${v}%"></div></div><strong>${v}</strong></div>`).join("")}<h3>Roadmap</h3>${SCENARIO.phases.map((x,i)=>`<button class="navbtn roadmap ${i===state.phase?'current':state.done[x.id]?'done':''}" onclick="setPhase(${i})">${i===state.phase?'►':state.done[x.id]?'✓':'○'} Phase ${x.number}: ${esc(x.title)}<div class="meta">${esc(x.phaseLabel || ('Phase '+x.number))}</div></button>`).join("")}<button class="navbtn" onclick="reset()">Reset</button></aside>`}
function coach(){let pc=pct();return `<aside class="card coach"><h2>Coach</h2><span class="pill purple">Purpose</span><p>${esc(p().purpose)}</p><div class="result"><strong>Expert Tip:</strong> ${esc(p().tip)}</div><h3>Checklist <span class="pill ${pc===100?'green':'yellow'}">${pc}%</span></h3><div class="bar"><div class="fill" style="width:${pc}%"></div></div>${p().checklist.map((x,i)=>{let c=state.check[p().id+":"+i];return `<label class="check-item ${c?'checked':''}"><input type="checkbox" ${c?'checked':''} onchange="toggleCheck(${i})"><span>${esc(x)}</span></label>`}).join("")}</aside>`}
function scenarioCard(){let ob=o();return `<div class="card hero"><div class="meta">${esc(p().phaseLabel || ('Phase '+p().number))} · Observation ${state.obs+1} of ${p().observations.length}</div><h2>🔎 What You Notice</h2><h3>${esc(ob.title)}</h3><div class="notice-card"><div class="soft"><h4>What you see</h4><ul>${ob.notice.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div><div class="soft"><h4>Why this caught your attention</h4><p>${esc(ob.attention)}</p></div></div><div class="soft questions"><h4>Questions you might ask</h4>${ob.questions.map(q=>`<label><input type="checkbox"> ${esc(q)}</label>`).join("")}</div>${ob.context?.length?`<details class="soft"><summary><strong>More context</strong></summary><ul>${ob.context.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></details>`:""}</div>`}
function workspace(){return `<div class="card workspace"><h3>📝 Your CIC Notes</h3><div class="field"><label>What seems important?</label><textarea oninput="note('important',this.value)">${esc(getNote('important'))}</textarea></div><div class="field"><label>What would you investigate next?</label><textarea oninput="note('investigate',this.value)">${esc(getNote('investigate'))}</textarea></div><div class="field"><label>Possible risk or downstream impact</label><textarea oninput="note('risk',this.value)">${esc(getNote('risk'))}</textarea></div><button class="primary" onclick="reveal()">Reveal Senior CIC Perspective</button></div>`}
function senior(){if(!isRevealed())return "";let ob=o();return `<div class="card senior"><h3>👨‍🏫 Senior CIC Perspective</h3><div class="result">${esc(ob.senior)}</div><h3>⭐ What Good Looks Like</h3><ul>${ob.good.map(x=>`<li>${esc(x)}</li>`).join("")}</ul><button class="ghost" onclick="prevObs()">← Previous Observation</button> <button class="primary" onclick="nextObs()">Next Observation →</button></div>`}
function main(){return `<main>${scenarioCard()}${workspace()}${senior()}</main>`}
function render(){let el=document.getElementById("app");if(!state.started){el.innerHTML=landing();return}el.innerHTML=`<header><h1>${esc(SCENARIO.appName)}</h1><p>Phase-Based CIC Apprenticeship</p></header><div class="shell">${sidebar()}${main()}${coach()}</div><div class="footer">Progress saves locally in your browser.</div>`}
render();
